### ISSUE TITLE
Release, please?

### ISSUE THREAD

**Issue by Lukas1h** [James-Livesey/Sinecraft#11]
Due to my computer setup, I'm having a hard time setting up fxSDK. I would love to test this out though. Could you possibly provide a release?

Thanks! 😁

**Comment by James-Livesey** [comment]
Hi Lukas1h,

I've just [created a new release](https://github.com/James-Livesey/Sinecraft/releases/tag/0.1.0) for you to test out — I too found it initially a bit difficult getting fxSDK working when I started working on Sinecraft so I understand the struggle!

There's only a .g1a file that I can provide at the moment, so I hope it works on your calculator (though of course note that this is highly unlikely to work with colour calculators like the fx-CG50).

Have fun and let me know what you think!

-James.

**Comment by Lukas1h** [comment]
Got it downloaded.

Great job with the game. Looks very reminiscent of the original PE version that I used to love to play.

On average, what FPS is it suppose to run at? I'm only getting about 2 FPS on my fx-9750GIII.

Also, what are the default controls?

**Comment by James-Livesey** [comment]
Glad to hear it works! Yeah, the FPS is pretty low, and 2 FPS is pretty normal for the default world atm (you have the same calculator as me it seems) — it's my first time writing a 3D renderer, so it's definitely in need of a rewrite! If you destroy blocks, the FPS increases (press and hold the <kbd>DEL</kbd> key).

Controls-wise, use <kbd>8</kbd>, <kbd>4</kbd>, <kbd>5</kbd> and <kbd>6</kbd> to move around, <kbd>÷</kbd> to jump, <kbd>OPTN</kbd> to open the inventory, <kbd>VARS</kbd> for crafting (also opens crafting tables when facing one), <kbd>F1</kbd>-<kbd>F6</kbd> to select items in the hotbar, <kbd>AC/ON</kbd> to place blocks, and of course <kbd>DEL</kbd> to destroy them.

There's also a few bits of info on [the wiki](https://github.com/James-Livesey/Sinecraft/wiki) which you can check out, and if you have any more questions, feel free to ask!

**Comment by Lukas1h** [comment]
Deleting a few blocks helped the fps quite a bit. I thought maybe decreasing the fov would help to, but I didn't really notice much of a difference.

A section in the wiki about controls might be a good addition.

**Comment by James-Livesey** [comment]
Good point! Just added a section to the wiki for the controls: https://github.com/James-Livesey/Sinecraft/wiki/Controls
